version: "3.9"

services:
  web:
    image: nginx:alpine
    volumes:
      - "./frontend/public:/usr/share/nginx/html"
      - "./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      # TODO: 443 to 80
      - "8000:80"  # temporary

  api:
    build:
      context: ./backend
